import("System")
import("System.TimeSpan")

luanet.load_assembly("CLEditor.Core")
import("CLEngine")
import("CLEditor")
import("CLEditor.Core")
import("CLEditor.Core.QuadTree")
import("CLEditor.Core.Diagnostics")
import("CLEditor.Core.Diagnostics.GlobalLogger")

luanet.load_assembly("MonoGame.Framework")
import("Microsoft.Xna.Framework")
import("Microsoft.Xna.Framework.Graphics")
import("Microsoft.Xna.Framework.Graphics.SamplerState")
import("Microsoft.Xna.Framework.Color")
import("Microsoft.Xna.Framework.Texture2D")
import("Microsoft.Xna.Framework.Graphics.GraphicsProfile")
import("Microsoft.Xna.Framework.Input")
import("Microsoft.Xna.Framework.Input.Keys")
import("Microsoft.Xna.Framework.Audio")

luanet.load_assembly("DragonBonesMG")
import("DragonBonesMG")
import("DragonBonesMG.Core")

luanet.load_assembly("VelcroPhysics.MonoGame")
import("VelcroPhysics.Dynamics")
import("VelcroPhysics.Factories")
import("VelcroPhysics.Dynamics.BodyType")