/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package rg_HuoShan.YongHu.MoRen;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int mbult4gvm5za89di=0x7f020000;
    }
    public static final class id {
        public static final int rg_biaoqian=0x7f040001;
        public static final int rg_qidonglei=0x7f040000;
    }
    public static final class layout {
        public static final int rg_qidonglei=0x7f030000;
    }
}
